version: '2.4'
services:
  web:
    build: .
    volumes:
      - .:/authdio
    tty: true
    command: python app.py
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local